#!/bin/sh

semaphore=/tmp/container-initialized
interval=$1

shift

command="$@"

if [ -f $semaphore ]; then
    sleep $interval
    eval "$@"

    exit $?
fi

exit_code=1
time=$(date +%s)

while [ $exit_code -ne 0 ]; do
    if [ $(($(date +%s) - time)) -ge $interval ]; then
        exit 1
    fi

    sleep 1

    eval "$@"

    exit_code=$?
done

touch $semaphore
